### ISSUE TITLE
Error while creating a document

### ISSUE THREAD

**Issue by baracaio** [clicksign/clicksign-php#7]
I'm facing a problem while testing the library to integrate it to my project.

The following GIST contains the cURL verbose content and the code I'm using.
All the code is based on the sample included.

https://gist.github.com/baracaio/8e225f1612de1bbcf06a2a588fb7689d

EDIT
Here's the stack trace thrown from the application

> PHP Fatal error:  Uncaught Clicksign\ClicksignException: Expected status [200], actual status [500], URL [/documents] in /var/www/test/vendor/clicksign/clicksign-php/src/Clicksign/ClientBase.php:136
Stack trace:
#0 /var/www/test/vendor/clicksign/clicksign-php/src/Clicksign/ClientBase.php(94): Clicksign\ClientBase->parseResponse('/documents', 'HTTP/1.1 100 Co...', 200)
#1 /var/www/test/vendor/clicksign/clicksign-php/src/Clicksign/Services/Documents.php(71): Clicksign\ClientBase->request('/documents', 'POST', Array, 200, 'multipart/mixed...')
#2 /var/www/test/vendor/clicksign/clicksign-php/src/Clicksign/Services/Documents.php(36): Clicksign\Services\Documents->_upload('./2018-04-17-11...')
#3 /var/www/test/index.php(19): Clicksign\Services\Documents->upload('./2018-04-17-11...')
#4 {main}
  thrown in /var/www/test/vendor/clicksign/clicksign-php/src/Clicksign/ClientBase.php on line 136

**Comment by mbbernstein** [comment]
@baracaio, por favor envie um email para suporte@clicksign.com com os dados da sua conta para verificarmos nos logs o que está ocorrendo.
