### ISSUE TITLE
Acesso não autorizado

### ISSUE THREAD

**Issue by igordelorenzi** [clicksign/clicksign-php#8]
O retorno do seguinte trecho de código as vezes é `Expected status [200], actual status [401], URL [/documents]`, e as vezes é `NULL`:
```php
try {
    $client = new Client();
    $client->setUrl('https://app.clicksign.com/');
    $client->setAccessToken('meu_access_token');

    $docs = $client->documents->all();
    var_dump($docs);
    exit;
} catch (Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}
```
Preciso de ajuda pra entender o que pode estar errado.

**Comment by mbbernstein** [comment]
@igordelorenzi Essa requisição funciona normalmente pelo Postman ou curl?

**Comment by igordelorenzi** [comment]
Sim, @mbbernstein, pelo CURL funciona normalmente. Inclusive, eu usei o [Guzzle](https://github.com/guzzle/guzzle) para implementar a API e deu tudo certo!

**Comment by mbbernstein** [comment]
@igordelorenzi   Essa biblioteca foi descontinuada.
